"""Idempotent provisioner for the LightSail Paper + Geyser + Floodgate Minecraft server.

Invocation::

    sudo python3 scripts/server/install.py
    sudo python3 scripts/server/install.py --mc-version 1.21.8 --paper-build 60
    sudo python3 scripts/server/install.py --dry-run

This script runs on the LightSail instance after Terraform has provisioned the instance and the data volume has
been re-attached and mounted at ``/srv/minecraft``. It does NOT touch AWS resources; those live in ``infra/``.

Idempotent: every mutation step inspects current state and skips when the desired state is already in place.
Re-running converges to the same end state without error. ``--dry-run`` prints every mutation the script would
perform.

Pin policy: Paper, Geyser, Floodgate, and ViaVersion versions are pinned via CLI flags. Defaults read from the
data volume (Paper from ``version_history.json``; plugins from each jar's ``plugin.yml``). The script never
auto-bumps versions; that is the future nightly updater's job.

CRITICAL: ``plugins/floodgate/key.pem`` must be preserved across rebuilds. The script refuses to proceed if it is
absent (override with ``--allow-fresh-floodgate-key`` for a brand-new environment where Floodgate will generate
one on first start). Geyser and Floodgate share this key for Bedrock auth; regenerating it breaks login for every
existing Bedrock player.
"""

from __future__ import annotations

import argparse
import os
import shlex
import subprocess
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from _common import (
    FLOODGATE_API_BASE,
    GEYSER_API_BASE,
    VERSION_HISTORY_FILE,
    ChecksumMismatchError,
    DownloadError,
    JarArtifact,
    fetch_geyser_like_artifact,
    fetch_paper_artifact,
    fetch_viaversion_artifact,
    http_download_to_file,
    http_get,
    read_mc_version_from_history,
    sha256_of_file,
)

# --- Constants ---------------------------------------------------------------

DEFAULT_DATA_ROOT = Path("/srv/minecraft")
SERVER_SUBDIR = "server"
PLUGINS_SUBDIR = "plugins"
PAPER_JAR_NAME = "paper.jar"
START_SCRIPT_NAME = "start.sh"
EULA_FILENAME = "eula.txt"
EULA_CONTENT = "eula=true\n"

DEFAULT_USER = "minecraft"
DEFAULT_GROUP = "minecraft"
DEFAULT_SHELL = "/usr/sbin/nologin"
DEFAULT_HEAP = "6G"

CORRETTO_KEYRING_PATH = Path("/usr/share/keyrings/corretto-keyring.gpg")
CORRETTO_KEY_URL = "https://apt.corretto.aws/corretto.key"
CORRETTO_REPO_PATH = Path("/etc/apt/sources.list.d/corretto.list")
CORRETTO_REPO_LINE = "deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main\n"
JAVA_PACKAGE = "java-21-amazon-corretto-jdk"
COMMON_PACKAGES: tuple[str, ...] = ("unzip", "wget", "ca-certificates", "gnupg")

SYSTEMD_UNIT_PATH = Path("/etc/systemd/system/minecraft.service")
SYSTEMD_UNIT_NAME = "minecraft.service"

UPDATER_SOURCE_FILES: tuple[str, ...] = ("update.py", "_common.py")
UPDATER_INSTALL_DIR = Path("/usr/local/sbin")
UPDATER_SCRIPT_NAME = "minecraft-update.py"
UPDATER_SCRIPT_PATH = UPDATER_INSTALL_DIR / UPDATER_SCRIPT_NAME

SYSTEMD_UNIT_TEMPLATE = """\
[Unit]
Description=Minecraft Paper Server (Paper + Geyser + Floodgate)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={user}
Group={group}
WorkingDirectory={server_dir}
ExecStart={server_dir}/start.sh
Restart=on-failure
RestartSec=10
Nice=5
LimitNOFILE=100000

[Install]
WantedBy=multi-user.target
"""

START_SCRIPT_TEMPLATE = """\
#!/usr/bin/env bash
# Generated by scripts/server/install.py — re-run the script to regenerate.
set -euo pipefail
cd {server_dir}
exec /usr/bin/java -Xms{heap} -Xmx{heap} -jar {server_dir}/{paper_jar} --nogui
"""


# --- Exceptions --------------------------------------------------------------


class InstallError(RuntimeError):
    """Base class for installer errors. Caught at the CLI boundary."""


class PreflightError(InstallError):
    """Raised when a pre-flight assertion fails (root, OS, mount)."""


class FloodgateKeyMissingError(InstallError):
    """Raised when ``plugins/floodgate/key.pem`` is missing without override."""


class VersionDiscoveryError(InstallError):
    """Raised when a required version cannot be discovered from CLI or volume."""


# --- Datatypes ---------------------------------------------------------------


@dataclass(frozen=True)
class InstallPaths:
    """Resolved on-disk locations the installer operates against.

    Attributes:
        data_root: Mountpoint of the data volume (default ``/srv/minecraft``).
        server_dir: Paper server directory (``data_root/server``).
        plugins_dir: Plugins directory (``server_dir/plugins``).
        paper_jar: Path to the running Paper jar.
        start_script: Path to the launcher script ``start.sh``.
        eula_file: Path to ``eula.txt``.
    """

    data_root: Path
    server_dir: Path
    plugins_dir: Path
    paper_jar: Path
    start_script: Path
    eula_file: Path

    @classmethod
    def from_data_root(cls, data_root: Path) -> "InstallPaths":
        """Build an ``InstallPaths`` from the volume root.

        Args:
            data_root: Mountpoint of the data volume.

        Returns:
            A fully-populated ``InstallPaths``.
        """
        server_dir = data_root / SERVER_SUBDIR
        return cls(
            data_root=data_root,
            server_dir=server_dir,
            plugins_dir=server_dir / PLUGINS_SUBDIR,
            paper_jar=server_dir / PAPER_JAR_NAME,
            start_script=server_dir / START_SCRIPT_NAME,
            eula_file=server_dir / EULA_FILENAME,
        )


# --- Subprocess wrapper ------------------------------------------------------


def run_command(
    argv: Sequence[str],
    *,
    check: bool = True,
    capture: bool = False,
    dry_run: bool = False,
    input_text: str | None = None,
) -> subprocess.CompletedProcess[str]:
    """Run a local command, honoring ``--dry-run`` for mutating invocations.

    Args:
        argv: Command tokens. The first element is the executable.
        check: When true, raise ``CalledProcessError`` on non-zero exit. Use ``False`` for state-query commands
            where non-zero is informational.
        capture: When true, capture stdout/stderr as text. When false, the child process inherits the parent's
            stdio.
        dry_run: When true, log the command to stderr and return a zero-exit stub without executing. Callers
            should set this for mutating invocations only — read-only state queries should always run.
        input_text: Optional stdin to pipe in.

    Returns:
        The ``CompletedProcess``. In dry-run mode, ``returncode`` is ``0`` and stdout/stderr are empty strings.
    """
    rendered = " ".join(shlex.quote(t) for t in argv)
    if dry_run:
        print(f"[dry-run] {rendered}", file=sys.stderr)
        return subprocess.CompletedProcess(args=list(argv), returncode=0, stdout="", stderr="")
    print(f"[run] {rendered}", file=sys.stderr)
    return subprocess.run(  # noqa: S603 — argv passed as list, no shell.
        list(argv),
        check=check,
        capture_output=capture,
        text=True,
        input=input_text,
    )


# --- Pre-flight checks -------------------------------------------------------


def assert_root() -> None:
    """Refuse to proceed unless the process is running as UID 0.

    Raises:
        PreflightError: When ``geteuid()`` is non-zero.
    """
    if os.geteuid() != 0:
        raise PreflightError("install.py must run as root (re-invoke with sudo)")


def assert_ubuntu_2204(os_release_text: str) -> None:
    """Confirm the host is Ubuntu 22.04 by parsing ``/etc/os-release`` content.

    Args:
        os_release_text: Full content of ``/etc/os-release``.

    Raises:
        PreflightError: When the file does not identify an Ubuntu 22.04 host.
    """
    fields = parse_os_release(os_release_text)
    distro = fields.get("ID", "").strip().lower()
    version = fields.get("VERSION_ID", "").strip().strip('"')
    if distro != "ubuntu" or version != "22.04":
        raise PreflightError(f"unsupported OS: ID={distro!r} VERSION_ID={version!r}; expected ubuntu 22.04")


def parse_os_release(text: str) -> dict[str, str]:
    """Parse a simple ``KEY=VALUE`` os-release file.

    Args:
        text: Full file content.

    Returns:
        Dict of keys to unquoted values. Lines without ``=`` are ignored.
    """
    parsed: dict[str, str] = {}
    for raw in text.splitlines():
        if "=" not in raw or raw.lstrip().startswith("#"):
            continue
        key, _, value = raw.partition("=")
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        parsed[key] = value
    return parsed


def assert_volume_mounted(data_root: Path, mounts_text: str) -> None:
    """Confirm ``data_root`` is the mountpoint of a real filesystem (not the rootfs).

    Reads ``/proc/mounts``-style content. The intent is to refuse to write into a directory that's just a
    placeholder on the rootfs — world data must live on the attached block storage.

    Args:
        data_root: Expected mountpoint of the data volume.
        mounts_text: Content of ``/proc/mounts`` (or equivalent).

    Raises:
        PreflightError: When ``data_root`` does not appear as its own mount.
    """
    target = str(data_root)
    for line in mounts_text.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[1] == target:
            return
    raise PreflightError(
        f"{data_root} is not a mountpoint — re-attach the data volume and verify the fstab entry "
        "before re-running install.py"
    )


# --- Apt operations ----------------------------------------------------------


def install_corretto_keyring(*, dry_run: bool = False) -> bool:
    """Install the Corretto apt signing keyring under ``/usr/share/keyrings/``.

    Idempotent: skipped when the keyring file already exists.

    Args:
        dry_run: When true, log the planned mutations without performing them.

    Returns:
        ``True`` when the keyring was installed by this call, ``False`` when it was already present.

    Raises:
        DownloadError: When the key cannot be fetched.
    """
    if CORRETTO_KEYRING_PATH.exists():
        print(f"[skip] {CORRETTO_KEYRING_PATH} already present", file=sys.stderr)
        return False
    if dry_run:
        print(f"[dry-run] download {CORRETTO_KEY_URL} → gpg --dearmor → {CORRETTO_KEYRING_PATH}", file=sys.stderr)
        return True
    key_bytes = http_get(CORRETTO_KEY_URL)
    CORRETTO_KEYRING_PATH.parent.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run(  # noqa: S603 — argv as list, no shell.
        ["gpg", "--dearmor", "--output", str(CORRETTO_KEYRING_PATH)],
        input=key_bytes,
        capture_output=True,
        check=False,
    )
    if proc.returncode != 0:
        stderr = proc.stderr.decode("utf-8", errors="replace")
        raise InstallError(f"gpg --dearmor failed (rc={proc.returncode}): {stderr}")
    CORRETTO_KEYRING_PATH.chmod(0o644)
    return True


def install_corretto_repo(*, dry_run: bool = False) -> bool:
    """Install the Corretto apt source list under ``/etc/apt/sources.list.d/``.

    Idempotent: skipped when the existing file already matches the desired line.

    Args:
        dry_run: When true, log the planned write without performing it.

    Returns:
        ``True`` when the file was written by this call, ``False`` when no change was needed.
    """
    return write_file_if_changed(
        CORRETTO_REPO_PATH,
        CORRETTO_REPO_LINE,
        owner_user=None,
        owner_group=None,
        mode=0o644,
        dry_run=dry_run,
    )


def apt_update(*, dry_run: bool = False) -> None:
    """Run ``apt-get update`` non-interactively.

    Args:
        dry_run: Honored — prints the command without running it.
    """
    run_command(
        ["env", "DEBIAN_FRONTEND=noninteractive", "apt-get", "update"],
        dry_run=dry_run,
    )


def apt_packages_installed(packages: Sequence[str]) -> dict[str, bool]:
    """Return a mapping of package name → whether ``dpkg -s`` reports installed.

    Args:
        packages: Package names to query.

    Returns:
        Mapping of name to install status. Missing packages map to ``False``.
    """
    result: dict[str, bool] = {}
    for pkg in packages:
        proc = subprocess.run(  # noqa: S603 — argv as list, no shell.
            ["dpkg", "-s", pkg],
            capture_output=True,
            text=True,
            check=False,
        )
        result[pkg] = proc.returncode == 0 and "Status: install ok installed" in proc.stdout
    return result


def apt_install(packages: Sequence[str], *, dry_run: bool = False) -> Sequence[str]:
    """Install ``packages`` via apt, skipping any already installed.

    Args:
        packages: Package names to install.
        dry_run: When true, log the planned install without performing it.

    Returns:
        The list of packages that were actually installed (i.e. were missing before the call). Empty when nothing
        needed installing.
    """
    statuses = apt_packages_installed(packages)
    missing = [p for p, installed in statuses.items() if not installed]
    if not missing:
        print(f"[skip] all packages already installed: {', '.join(packages)}", file=sys.stderr)
        return ()
    run_command(
        ["env", "DEBIAN_FRONTEND=noninteractive", "apt-get", "install", "-y", "--no-install-recommends", *missing],
        dry_run=dry_run,
    )
    return tuple(missing)


# --- User / group operations -------------------------------------------------


def group_exists(name: str) -> bool:
    """Return whether a system group named ``name`` exists.

    Args:
        name: Group name.

    Returns:
        ``True`` when ``getent group <name>`` returns success.
    """
    proc = subprocess.run(  # noqa: S603 — argv as list, no shell.
        ["getent", "group", name],
        capture_output=True,
        check=False,
    )
    return proc.returncode == 0


def user_exists(name: str) -> bool:
    """Return whether a system user named ``name`` exists.

    Args:
        name: User name.

    Returns:
        ``True`` when ``getent passwd <name>`` returns success.
    """
    proc = subprocess.run(  # noqa: S603 — argv as list, no shell.
        ["getent", "passwd", name],
        capture_output=True,
        check=False,
    )
    return proc.returncode == 0


def ensure_group(name: str, *, dry_run: bool = False) -> bool:
    """Create a system group if it does not already exist.

    Args:
        name: Group name to create.
        dry_run: When true, log the planned mutation without performing it.

    Returns:
        ``True`` when the group was created by this call, ``False`` when it was already present.
    """
    if group_exists(name):
        print(f"[skip] group {name!r} already exists", file=sys.stderr)
        return False
    run_command(["groupadd", "--system", name], dry_run=dry_run)
    return True


def ensure_user(
    name: str,
    *,
    group: str,
    home: Path,
    shell: str,
    dry_run: bool = False,
) -> bool:
    """Create a system user with the given group, home, and shell if absent.

    Args:
        name: User name to create.
        group: Primary group (must already exist; create with ``ensure_group``).
        home: Home directory path. The directory is NOT created here.
        shell: Login shell (e.g. ``/usr/sbin/nologin``).
        dry_run: When true, log the planned mutation without performing it.

    Returns:
        ``True`` when the user was created by this call, ``False`` when it was already present.
    """
    if user_exists(name):
        print(f"[skip] user {name!r} already exists", file=sys.stderr)
        return False
    run_command(
        ["useradd", "--system", "--gid", group, "--home-dir", str(home), "--shell", shell, name],
        dry_run=dry_run,
    )
    return True


# --- File-write idempotency --------------------------------------------------


def write_file_if_changed(
    path: Path,
    content: str,
    *,
    owner_user: str | None,
    owner_group: str | None,
    mode: int,
    dry_run: bool = False,
) -> bool:
    """Write ``content`` to ``path`` only if the existing file differs.

    Compares as bytes after UTF-8 encoding. When the file is written, ownership and mode are applied.
    ``owner_user`` / ``owner_group`` may be ``None`` to leave ownership at the process default (root).

    Args:
        path: Target path.
        content: Desired UTF-8 text content.
        owner_user: Optional owning user name.
        owner_group: Optional owning group name.
        mode: Numeric mode bits (e.g. ``0o644``).
        dry_run: When true, log the planned write without performing it.

    Returns:
        ``True`` when the file was written by this call, ``False`` when the existing content already matched.
    """
    desired_bytes = content.encode("utf-8")
    if path.exists() and path.read_bytes() == desired_bytes:
        existing_mode = path.stat().st_mode & 0o7777
        if existing_mode == mode:
            print(f"[skip] {path} already at desired content + mode", file=sys.stderr)
            return False
    if dry_run:
        print(f"[dry-run] write {len(desired_bytes)} bytes to {path} (mode {oct(mode)})", file=sys.stderr)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(desired_bytes)
    path.chmod(mode)
    if owner_user and owner_group:
        run_command(["chown", f"{owner_user}:{owner_group}", str(path)])
    return True


def ensure_directory(
    path: Path,
    *,
    owner_user: str,
    owner_group: str,
    mode: int = 0o755,
    dry_run: bool = False,
) -> bool:
    """Create ``path`` and apply ownership/mode if it does not already exist.

    When the directory already exists, ownership is fixed only when wrong (one fewer subprocess on a re-run). The
    mode is fixed in the same way.

    Args:
        path: Directory to create.
        owner_user: Owning user.
        owner_group: Owning group.
        mode: Numeric mode bits.
        dry_run: When true, log the planned mutation without performing it.

    Returns:
        ``True`` when ``mkdir`` ran, ``False`` when the directory existed.
    """
    created = False
    if not path.exists():
        if dry_run:
            print(f"[dry-run] mkdir -p {path} (mode {oct(mode)} owner {owner_user}:{owner_group})", file=sys.stderr)
            return True
        path.mkdir(parents=True, exist_ok=True)
        created = True
    if not dry_run:
        path.chmod(mode)
        run_command(["chown", f"{owner_user}:{owner_group}", str(path)])
    return created


# --- Download + place --------------------------------------------------------


def download_and_place_jar(
    artifact: JarArtifact,
    dest: Path,
    *,
    owner_user: str,
    owner_group: str,
    dry_run: bool = False,
) -> bool:
    """Download ``artifact`` to ``dest`` if missing or sha256-mismatched.

    Verifies the downloaded bytes against ``artifact.sha256`` and applies ownership. A pre-existing file with the
    matching hash is left in place.

    Args:
        artifact: Jar metadata.
        dest: Final on-disk path.
        owner_user: Owning user for the placed file.
        owner_group: Owning group for the placed file.
        dry_run: When true, log the planned download without performing it.

    Returns:
        ``True`` when the jar was downloaded by this call, ``False`` when the existing file already matched.

    Raises:
        ChecksumMismatchError: When the downloaded bytes do not match.
        DownloadError: When the HTTP fetch fails.
    """
    if dest.exists():
        observed = sha256_of_file(dest)
        if observed == artifact.sha256:
            print(f"[skip] {dest} already at sha256 {artifact.sha256[:12]}…", file=sys.stderr)
            return False
        print(f"[update] {dest} sha256 {observed[:12]}… → {artifact.sha256[:12]}…", file=sys.stderr)
    if dry_run:
        print(f"[dry-run] download {artifact.label} {artifact.version} → {dest}", file=sys.stderr)
        return True
    dest.parent.mkdir(parents=True, exist_ok=True)
    print(f"[download] {artifact.label} {artifact.version} → {dest}", file=sys.stderr)
    http_download_to_file(artifact.download_url, dest)
    observed = sha256_of_file(dest)
    if observed != artifact.sha256:
        dest.unlink()
        raise ChecksumMismatchError(
            f"{artifact.label} {artifact.version}: expected sha256 {artifact.sha256}, got {observed}"
        )
    run_command(["chown", f"{owner_user}:{owner_group}", str(dest)])
    return True


# --- Floodgate key check -----------------------------------------------------


def assert_floodgate_key_present(plugins_dir: Path, *, allow_fresh: bool) -> None:
    """Refuse to proceed when ``floodgate/key.pem`` is missing without override.

    Floodgate's ``key.pem`` signs Bedrock auth handshakes; Geyser's ``floodgate-key-file`` config points at it.
    Regenerating the key breaks login for every existing Bedrock player. The script preserves the volume's key
    when present; ``allow_fresh`` is required to opt into a brand-new environment where Floodgate will generate
    one on first start.

    Args:
        plugins_dir: Plugins directory (``data_root/server/plugins``).
        allow_fresh: When true, a missing key is acceptable (caller is standing up a brand-new environment, not
            rebuilding the live one).

    Raises:
        FloodgateKeyMissingError: When the key is absent and ``allow_fresh`` is false.
    """
    key_path = plugins_dir / "floodgate" / "key.pem"
    if key_path.exists():
        print(f"[ok] preserving Floodgate key at {key_path}", file=sys.stderr)
        return
    if allow_fresh:
        print(
            f"[warn] {key_path} missing; --allow-fresh-floodgate-key set, Floodgate will "
            "generate a new key on first start (existing Bedrock players will need to re-link)",
            file=sys.stderr,
        )
        return
    raise FloodgateKeyMissingError(
        f"{key_path} missing. The Floodgate key MUST be preserved across rebuilds, "
        "otherwise existing Bedrock players cannot log in. Restore the key from a "
        "snapshot, or pass --allow-fresh-floodgate-key if you are standing up a "
        "brand-new environment."
    )


# --- Configs -----------------------------------------------------------------


def ensure_eula(paths: InstallPaths, owner_user: str, owner_group: str, *, dry_run: bool = False) -> bool:
    """Write ``eula.txt`` accepting Mojang's EULA, idempotently.

    Args:
        paths: Resolved install paths.
        owner_user: Owning user for the file.
        owner_group: Owning group for the file.
        dry_run: When true, log the planned write without performing it.

    Returns:
        ``True`` when the file was written, ``False`` when it already matched.
    """
    return write_file_if_changed(
        paths.eula_file,
        EULA_CONTENT,
        owner_user=owner_user,
        owner_group=owner_group,
        mode=0o644,
        dry_run=dry_run,
    )


def render_start_script(server_dir: Path, heap: str) -> str:
    """Return the start-script content for the given server dir + heap.

    Args:
        server_dir: Server directory containing the Paper jar.
        heap: Heap-size string (e.g. ``"6G"``).

    Returns:
        Rendered shell-script content with a trailing newline.
    """
    return START_SCRIPT_TEMPLATE.format(server_dir=server_dir, heap=heap, paper_jar=PAPER_JAR_NAME)


def ensure_start_script(
    paths: InstallPaths,
    *,
    heap: str,
    owner_user: str,
    owner_group: str,
    dry_run: bool = False,
) -> bool:
    """Write ``start.sh`` with the requested heap size, idempotently.

    Args:
        paths: Resolved install paths.
        heap: Heap-size string.
        owner_user: Owning user for the file.
        owner_group: Owning group for the file.
        dry_run: When true, log the planned write without performing it.

    Returns:
        ``True`` when the file was written, ``False`` when it already matched.
    """
    content = render_start_script(paths.server_dir, heap)
    return write_file_if_changed(
        paths.start_script,
        content,
        owner_user=owner_user,
        owner_group=owner_group,
        mode=0o750,
        dry_run=dry_run,
    )


def render_systemd_unit(server_dir: Path, user: str, group: str) -> str:
    """Return the systemd unit content for the given server dir + user/group.

    Args:
        server_dir: Server directory.
        user: Service user.
        group: Service group.

    Returns:
        Rendered unit content with a trailing newline.
    """
    return SYSTEMD_UNIT_TEMPLATE.format(server_dir=server_dir, user=user, group=group)


def ensure_systemd_unit(
    paths: InstallPaths,
    *,
    user: str,
    group: str,
    dry_run: bool = False,
) -> bool:
    """Write the systemd unit, idempotently.

    Args:
        paths: Resolved install paths.
        user: Service user.
        group: Service group.
        dry_run: When true, log the planned write without performing it.

    Returns:
        ``True`` when the unit file was written, ``False`` when it already matched. Callers use the return to
        decide whether ``daemon-reload`` is needed.
    """
    content = render_systemd_unit(paths.server_dir, user, group)
    return write_file_if_changed(
        SYSTEMD_UNIT_PATH,
        content,
        owner_user=None,
        owner_group=None,
        mode=0o644,
        dry_run=dry_run,
    )


# --- Updater deployment ------------------------------------------------------


def deploy_updater(source_dir: Path, *, dry_run: bool = False) -> bool:
    """Copy ``update.py`` and ``_common.py`` from ``source_dir`` to ``UPDATER_INSTALL_DIR``.

    Both files travel together: ``update.py`` is renamed to ``minecraft-update.py`` at the destination so
    the systemd ``ExecStart=`` path matches operator expectations; ``_common.py`` lands beside it so the
    script's same-dir import resolves at runtime. The copy is idempotent — files are rewritten only when
    their content differs from the existing on-disk file.

    Args:
        source_dir: Directory containing the source files. Typically ``Path(__file__).parent``.
        dry_run: When true, log the planned copies without performing them.

    Returns:
        ``True`` when any file was written by this call, ``False`` when every destination already matched.

    Raises:
        InstallError: When a source file is missing.
    """
    UPDATER_INSTALL_DIR.mkdir(parents=True, exist_ok=True)
    any_changed = False
    for source_name in UPDATER_SOURCE_FILES:
        source_path = source_dir / source_name
        if not source_path.exists():
            raise InstallError(f"updater source file missing: {source_path}")
        dest_name = UPDATER_SCRIPT_NAME if source_name == "update.py" else source_name
        dest_path = UPDATER_INSTALL_DIR / dest_name
        mode = 0o755 if source_name == "update.py" else 0o644
        source_bytes = source_path.read_bytes()
        if dest_path.exists() and dest_path.read_bytes() == source_bytes:
            existing_mode = dest_path.stat().st_mode & 0o7777
            if existing_mode == mode:
                print(f"[skip] {dest_path} already matches {source_path.name}", file=sys.stderr)
                continue
        if dry_run:
            print(f"[dry-run] copy {source_path} → {dest_path} (mode {oct(mode)})", file=sys.stderr)
            any_changed = True
            continue
        dest_path.write_bytes(source_bytes)
        dest_path.chmod(mode)
        print(f"[copy] {source_path} → {dest_path}", file=sys.stderr)
        any_changed = True
    return any_changed


def invoke_updater_install_systemd_units(*, dry_run: bool = False) -> None:
    """Run ``minecraft-update.py --install-systemd-units`` once via subprocess.

    The updater's self-install mode is fully idempotent on its own — repeat calls produce no side effects
    when units are already current — so this caller does not need to gate on whether it ran before.

    Args:
        dry_run: When true, log the command without executing it.
    """
    run_command(
        [sys.executable, str(UPDATER_SCRIPT_PATH), "--install-systemd-units"],
        dry_run=dry_run,
    )


# --- Service lifecycle -------------------------------------------------------


def systemctl_daemon_reload(*, dry_run: bool = False) -> None:
    """Run ``systemctl daemon-reload``.

    Args:
        dry_run: When true, log the command without running it.
    """
    run_command(["systemctl", "daemon-reload"], dry_run=dry_run)


def systemctl_enable_now(unit: str, *, dry_run: bool = False) -> None:
    """Enable and start a systemd unit.

    Args:
        unit: Unit name (e.g. ``minecraft.service``).
        dry_run: When true, log the command without running it.
    """
    run_command(["systemctl", "enable", "--now", unit], dry_run=dry_run)


# --- Main orchestration ------------------------------------------------------


@dataclass(frozen=True)
class ResolvedVersions:
    """Versions and builds the installer will use this run.

    Attributes:
        mc_version: Minecraft version (e.g. ``"1.21.8"``).
        paper_build: Paper build identifier (number, or ``"latest"``).
        geyser_version: Pinned Geyser version, or ``None`` for latest.
        geyser_build: Pinned Geyser build, or ``None`` for latest.
        floodgate_version: Pinned Floodgate version, or ``None`` for latest.
        floodgate_build: Pinned Floodgate build, or ``None`` for latest.
        viaversion_name: Pinned ViaVersion Hangar version name, or ``None``.
    """

    mc_version: str
    paper_build: int | str
    geyser_version: str | None
    geyser_build: int | None
    floodgate_version: str | None
    floodgate_build: int | None
    viaversion_name: str | None


def resolve_versions(args: argparse.Namespace, paths: InstallPaths) -> ResolvedVersions:
    """Pin every artifact's version, defaulting from the volume when available.

    Args:
        args: Parsed CLI arguments.
        paths: Resolved install paths.

    Returns:
        A populated ``ResolvedVersions``.

    Raises:
        VersionDiscoveryError: When ``--mc-version`` is not provided and the volume does not contain
            ``version_history.json`` to discover from.
    """
    mc_version = args.mc_version
    paper_build: int | str = args.paper_build if args.paper_build is not None else "latest"
    if mc_version is None:
        discovered = read_mc_version_from_history(paths.server_dir)
        if discovered is None:
            raise VersionDiscoveryError(
                "--mc-version is required when the data volume has no "
                f"{paths.server_dir / VERSION_HISTORY_FILE} (brand-new environment). "
                "Pass the MC version you want to install."
            )
        mc_version, discovered_build = discovered
        if args.paper_build is None:
            paper_build = discovered_build
    return ResolvedVersions(
        mc_version=mc_version,
        paper_build=paper_build,
        geyser_version=args.geyser_version,
        geyser_build=args.geyser_build,
        floodgate_version=args.floodgate_version,
        floodgate_build=args.floodgate_build,
        viaversion_name=args.viaversion,
    )


def install(args: argparse.Namespace) -> int:
    """Run the full provisioning pipeline.

    Args:
        args: Parsed CLI arguments.

    Returns:
        Process exit code. ``0`` on success.

    Raises:
        InstallError: Surfaced from any step. ``main`` catches and converts to a non-zero exit code.
    """
    paths = InstallPaths.from_data_root(args.data_root)

    # Pre-flight.
    assert_root()
    assert_ubuntu_2204(Path("/etc/os-release").read_text(encoding="utf-8"))
    if not args.skip_volume_check:
        assert_volume_mounted(paths.data_root, Path("/proc/mounts").read_text(encoding="utf-8"))

    # Apt: keyring → repo → update → install.
    keyring_added = install_corretto_keyring(dry_run=args.dry_run)
    repo_added = install_corretto_repo(dry_run=args.dry_run)
    if keyring_added or repo_added:
        apt_update(dry_run=args.dry_run)
    apt_install([*COMMON_PACKAGES, JAVA_PACKAGE], dry_run=args.dry_run)

    # User + group + directory layout.
    ensure_group(args.minecraft_group, dry_run=args.dry_run)
    ensure_user(
        args.minecraft_user,
        group=args.minecraft_group,
        home=paths.data_root,
        shell=args.minecraft_shell,
        dry_run=args.dry_run,
    )
    ensure_directory(
        paths.server_dir,
        owner_user=args.minecraft_user,
        owner_group=args.minecraft_group,
        dry_run=args.dry_run,
    )
    ensure_directory(
        paths.plugins_dir,
        owner_user=args.minecraft_user,
        owner_group=args.minecraft_group,
        dry_run=args.dry_run,
    )

    # Floodgate key precondition (after directories exist so the path resolves).
    assert_floodgate_key_present(paths.plugins_dir, allow_fresh=args.allow_fresh_floodgate_key)

    # Versions.
    versions = resolve_versions(args, paths)
    print(f"[plan] mc={versions.mc_version} paper={versions.paper_build}", file=sys.stderr)

    # Paper.
    paper_artifact = fetch_paper_artifact(versions.mc_version, versions.paper_build)
    download_and_place_jar(
        paper_artifact,
        paths.paper_jar,
        owner_user=args.minecraft_user,
        owner_group=args.minecraft_group,
        dry_run=args.dry_run,
    )

    # Plugins.
    geyser_artifact = fetch_geyser_like_artifact(
        "geyser",
        GEYSER_API_BASE,
        version=versions.geyser_version,
        build=versions.geyser_build,
    )
    download_and_place_jar(
        geyser_artifact,
        paths.plugins_dir / geyser_artifact.filename,
        owner_user=args.minecraft_user,
        owner_group=args.minecraft_group,
        dry_run=args.dry_run,
    )
    floodgate_artifact = fetch_geyser_like_artifact(
        "floodgate",
        FLOODGATE_API_BASE,
        version=versions.floodgate_version,
        build=versions.floodgate_build,
    )
    download_and_place_jar(
        floodgate_artifact,
        paths.plugins_dir / floodgate_artifact.filename,
        owner_user=args.minecraft_user,
        owner_group=args.minecraft_group,
        dry_run=args.dry_run,
    )
    viaversion_artifact = fetch_viaversion_artifact(versions.viaversion_name)
    download_and_place_jar(
        viaversion_artifact,
        paths.plugins_dir / viaversion_artifact.filename,
        owner_user=args.minecraft_user,
        owner_group=args.minecraft_group,
        dry_run=args.dry_run,
    )

    # Configs + launcher.
    ensure_eula(paths, args.minecraft_user, args.minecraft_group, dry_run=args.dry_run)
    ensure_start_script(
        paths,
        heap=args.heap_size,
        owner_user=args.minecraft_user,
        owner_group=args.minecraft_group,
        dry_run=args.dry_run,
    )

    # Systemd unit + service lifecycle.
    unit_changed = ensure_systemd_unit(
        paths,
        user=args.minecraft_user,
        group=args.minecraft_group,
        dry_run=args.dry_run,
    )
    if unit_changed:
        systemctl_daemon_reload(dry_run=args.dry_run)
    systemctl_enable_now(SYSTEMD_UNIT_NAME, dry_run=args.dry_run)

    # Updater deployment: copy update.py + _common.py to /usr/local/sbin and invoke the updater's own
    # self-install mode to drop the systemd units. The updater is the source of truth for its unit content
    # so install.py never emits update-timer/service templates directly.
    deploy_updater(Path(__file__).resolve().parent, dry_run=args.dry_run)
    invoke_updater_install_systemd_units(dry_run=args.dry_run)
    return 0


# --- CLI ---------------------------------------------------------------------


def build_argument_parser() -> argparse.ArgumentParser:
    """Build the CLI parser.

    Returns:
        The configured ``argparse.ArgumentParser``.
    """
    parser = argparse.ArgumentParser(
        prog="install.py",
        description=(
            "Idempotent provisioner for the LightSail Paper + Geyser + Floodgate Minecraft server. Run as root "
            "after the data volume is mounted at /srv/minecraft."
        ),
    )
    parser.add_argument(
        "--data-root",
        type=Path,
        default=DEFAULT_DATA_ROOT,
        help=f"Mountpoint of the data volume (default: {DEFAULT_DATA_ROOT}).",
    )
    parser.add_argument("--minecraft-user", default=DEFAULT_USER, help=f"Service user (default: {DEFAULT_USER}).")
    parser.add_argument("--minecraft-group", default=DEFAULT_GROUP, help=f"Service group (default: {DEFAULT_GROUP}).")
    parser.add_argument(
        "--minecraft-shell",
        default=DEFAULT_SHELL,
        help=f"Login shell for the service user (default: {DEFAULT_SHELL}).",
    )
    parser.add_argument("--heap-size", default=DEFAULT_HEAP, help=f"JVM heap size (default: {DEFAULT_HEAP}).")
    parser.add_argument(
        "--mc-version",
        help=(
            "Pin the Minecraft version (e.g. 1.21.8). Defaults to the version recorded in version_history.json on "
            "the data volume."
        ),
    )
    parser.add_argument(
        "--paper-build",
        type=int,
        help=(
            "Pin the Paper build number. Defaults to the build recorded in version_history.json, falling back to "
            "'latest' for --mc-version."
        ),
    )
    parser.add_argument("--geyser-version", help="Pin the Geyser version (default: latest published).")
    parser.add_argument("--geyser-build", type=int, help="Pin the Geyser build number (default: latest in version).")
    parser.add_argument("--floodgate-version", help="Pin the Floodgate version (default: latest published).")
    parser.add_argument(
        "--floodgate-build",
        type=int,
        help="Pin the Floodgate build number (default: latest in version).",
    )
    parser.add_argument(
        "--viaversion",
        help="Pin the ViaVersion Hangar version name (default: latest Release-channel build).",
    )
    parser.add_argument(
        "--allow-fresh-floodgate-key",
        action="store_true",
        help=(
            "Permit a missing plugins/floodgate/key.pem (brand-new environment only). Default: refuse to proceed "
            "without the key — regenerating breaks Bedrock login."
        ),
    )
    parser.add_argument(
        "--skip-volume-check",
        action="store_true",
        help="Skip the assertion that --data-root is a real mountpoint. For testing.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print every mutation that would be performed without executing it.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Entry point.

    Args:
        argv: Optional CLI arg list. ``None`` reads from ``sys.argv``.

    Returns:
        Process exit code. ``0`` on success, ``2`` on pre-flight failure, ``3`` on download/checksum failure,
        ``1`` on any other install error.
    """
    parser = build_argument_parser()
    args = parser.parse_args(argv)
    try:
        return install(args)
    except PreflightError as exc:
        print(f"pre-flight check failed: {exc}", file=sys.stderr)
        return 2
    except (DownloadError, ChecksumMismatchError) as exc:
        print(f"download failed: {exc}", file=sys.stderr)
        return 3
    except FloodgateKeyMissingError as exc:
        print(f"floodgate key check failed: {exc}", file=sys.stderr)
        return 2
    except VersionDiscoveryError as exc:
        print(f"version discovery failed: {exc}", file=sys.stderr)
        return 2
    except InstallError as exc:
        print(f"install failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
